spring.application.name=database_connection

spring.datasource.url=jdbc:mysql://localhost:3306/CRUD_ENTIDADES
spring.datasource.username=root
spring.datasource.password=MySQLdejulian1472.

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true